name: Ceedling Testing
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Current Repo Clone
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Ceedling
        run: gem install ceedling
      - name: Run Unit Tests
        run: |
          CUR=$PWD;
          cd "./MatrixMCU/lib/fsm/ceedling"
          ceedling test:all


